version: '3.9'

services:
  textsearchdemo.server:
    image: ${DOCKER_REGISTRY-}textsearchdemoserver
    build:
      dockerfile: TextSearchDemo.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
    - overlay
  textsearchdemo.client:
    image: ${DOCKER_REGISTRY-}textsearchdemoclient
    build:
      context: TextSearchDemo.client
      dockerfile: ./Dockerfile
    ports:
    - 4200:4200
    volumes: 
    - ./textsearchdemo.client:/front-app
    networks:
    - overlay
    depends_on:
    - textsearchdemo.server

networks:
  overlay:
